branch-defaults:
  default:
    environment: flask-env-client
    group_suffix: null
global:
  application_name: client
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null